version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    volumes:
      - ./mosquitto:/mosquitto/config
    ports:
      - "1883:1883"
      - "9001:9001"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    restart: unless-stopped